### ISSUE TITLE
readme doesn't give usage for most reporter-options

### ISSUE THREAD

**Issue by diggoran** [Infragistics/mocha-trx-reporter#10]
It took a lot of trial and error to figure out how to use `treatPendingAsNotExecuted` in conjunction with `output`. There should simply be an example of using more than one option at once in the readme.

`--reporter-options treatPendingAsNotExecuted,output=.\TestResults\result.trx`

**Comment by FabianTe** [comment]
Thank you!
I was wondering about this too!

**Comment by FabianTe** [comment]
I added a wiki page: https://github.com/Infragistics/mocha-trx-reporter/wiki/Options-usage

**Comment by pmoleri** [comment]
Thank you both for reporting the issue and the PR.
