### ISSUE TITLE
Vulnerability

### ISSUE THREAD

**Issue by morethanfire** [Infragistics/mocha-trx-reporter#15]
I am getting a couple vulnerabilities, low and moderate, when running `npm audit` with the mocha-trx-reporter package installed. It stems from an old version of lodash that is marked dependent and installed by xmlbuilder@2.6.5.

Moderate │ Prototype Pollution
mocha-trx-reporter > node-trx > xmlbuilder > lodash
https://npmjs.com/advisories/782

Low │ Prototype Pollution
mocha-trx-reporter > node-trx > xmlbuilder > lodash
https://npmjs.com/advisories/577

I realize that xmlbuilder is not your package, but was wondering if you were aware and if anything has been started with addressing the issue.

**Comment by pmoleri** [comment]
Hi @morethanfire I just submitted a PR and in the meanwhile created `@indigo/node-trx` with the updated dependencies.
You can now install `mocha-trx-reporter@3.2.1` with all warnings resolved.
