### ISSUE TITLE
Mocha-trx-reporter crashes when used from cypress

### ISSUE THREAD

**Issue by jessehouwing** [Infragistics/mocha-trx-reporter#9]
```
cypress --reporter mocha-trx-reporter 
```

Crashes with:
```
TypeError: test.isPending is not a function
    at C:\temp\node_modules\mocha-trx-reporter\lib\trx.js:63:22
    at Array.forEach (<anonymous>:null:null)
    at Runner.<anonymous> (C:\temp\node_modules\mocha-trx-reporter\lib\trx.js:62:34)
    at emitOne (events.js:120:20)
    at Runner.emit (events.js:210:7)
    at Reporter.emit (C:\temp\node_modules\cypress\dist\Cypress\resources\app\packages\server\lib\reporter.js:191:55)
    at Object.server.startWebsockets.onMocha (C:\temp\node_modules\cypress\dist\Cypress\resources\app\packages\server\lib\project.js:288:22)
    at Socket.<anonymous> (C:\temp\node_modules\cypress\dist\Cypress\resources\app\packages\server\lib\socket.js:237:36)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at C:\temp\node_modules\cypress\dist\Cypress\resources\app\packages\socket\node_modules\socket.io\lib\socket.js:503:12
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

I suspect it's because report contains nested Suites and it's trying to convert a Suite to a Test.

Our Cypress test looks like this:

```
describe('Hello world', () => {
  beforeEach(() => {
    cy.visit('/');
  });


  it('should show "Hello world"', () => {
    cy.get('#container').contains('Hello world');
  });
});
```
See also:  
* https://github.com/cypress-io/cypress/issues/1744

**Comment by SeriousM** [comment]
did you tried to workaround with the [`excludePending` option](https://www.npmjs.com/package/mocha-trx-reporter#usage)?

**Comment by jessehouwing** [comment]
Yes. No dice.

**Comment by WizX20** [comment]
Same issue here
`2019-09-02T18:44:17.1637752Z TypeError: test.isPending is not a function
2019-09-02T18:44:17.1639484Z     at testResults.tests.forEach (E:\agents\myagent-test-0\_work\r2\a\TESTS\release\node_modules\mocha-trx-reporter\lib\trx.js:92:22)
2019-09-02T18:44:17.1641447Z     at Array.forEach (<anonymous>:null:null)
2019-09-02T18:44:17.1643429Z     at Runner.ReporterTrx.runner.on (E:\agents\myagent-test-0\_work\r2\a\TESTS\release\node_modules\mocha-trx-reporter\lib\trx.js:91:27)
2019-09-02T18:44:17.1646632Z     at emitOne (events.js:121:20)
2019-09-02T18:44:17.1649120Z     at Runner.emit (events.js:211:7)
2019-09-02T18:44:17.1652497Z     at Reporter.emit (C:\Users\myagent-test\AppData\Local\Cypress\Cache\3.3.1\Cypress\resources\app\packages\server\lib\reporter.js:239:55)
2019-09-02T18:44:17.1656527Z     at Object.server.startWebsockets.onMocha (C:\Users\myagent-test\AppData\Local\Cypress\Cache\3.3.1\Cypress\resources\app\packages\server\lib\project.js:298:22)
2019-09-02T18:44:17.1659438Z     at Socket.<anonymous> (C:\Users\myagent-test\AppData\Local\Cypress\Cache\3.3.1\Cypress\resources\app\packages\server\lib\socket.js:235:36)
2019-09-02T18:44:17.1662081Z     at emitTwo (events.js:126:13)
2019-09-02T18:44:17.1665662Z     at Socket.emit (events.js:214:7)
2019-09-02T18:44:17.1668360Z     at C:\Users\myagent-test\AppData\Local\Cypress\Cache\3.3.1\Cypress\resources\app\packages\socket\node_modules\socket.io\lib\socket.js:503:12
2019-09-02T18:44:17.1671679Z     at _combinedTickCallback (internal/process/next_tick.js:131:7)
2019-09-02T18:44:17.1678187Z     at process._tickCallback (internal/process/next_tick.js:180:9)`

**Comment by pmoleri** [comment]
It seems that Cypress uses its own version of Mocha, instead of picking up the project's version:  https://github.com/cypress-io/cypress/issues/4652 and the version that Cypress includes doesn't have the isPending() method.

Some reporters are implemented using only events while other like [XUnit](https://mochajs.org/api/reporters_xunit.js.html) and mocha-trx-reporter are implemented using the `isPending()` method.

So, this could be solved by Cypress or by changing the way these reporters are implemented to not rely on `Runnable.isPending()` method. I'd prefer the former, but I would accept a pull request that changes this reporter to prevent this issue.

**Comment by pmoleri** [comment]
Update: mocha-trx-reporter was also bringing in its own mocha version, perhaps that was part of the issue too. This was changed in `v3.2.4` so perhaps this new version behaves properly even with Cypress.

Closing the issue now.

**Comment by smarandav** [comment]
@pmoleri I still have the same issue in mocha-trx-reporter version 3.2.4.
Is there a workaround for it?

**Comment by pmoleri** [comment]
@smarandav `mocha-trx-reporter` relies in `Runnable.isPending()` method that was introduced in [mocha@2.5.0](https://github.com/mochajs/mocha/blob/v2.5.0/lib/runnable.js#L140) 4 years ago.

I think you need to either:
 - Update to a Cypress version that uses a more recent version of Mocha.
   (you probably can check the version that Cypress is using by looking for _mocha_ in your `package-lock.json`)
 - Find a way to monkey patch the Runnable class to add the missing method.
   You can probably do this by requiring a local setup file in your https://mochajs.org/#mochaopts

If you choose to monkey patch to fix this issue, I can't tell you if some other issues will appear.

**Comment by smarandav** [comment]
@pmoleri thanks for your help

I have doubled checked and I am using latest version of mocha in both my packages that need it (cypress-multi-reporters, mocha-trx-reporter). 

When installing those two ^^ I do not have a hardcoded mocha dependency as per package-lock.json but still it complains about not finding the isPending() method.
"cypress-multi-reporters": {
      "version": "1.4.0",
      "resolved": "http://packages.je-labs.com/npm/private-npm/cypress-multi-reporters/-/cypress-multi-reporters-1.4.0.tgz",
      "integrity": "sha1-Xx0EhKIJWc/ngvG/Za0Wxq2ATac=",
      "dev": true,
      "requires": {
        "debug": "^4.1.1",
        "lodash": "^4.17.15"
      },

"mocha-trx-reporter": {
      "version": "3.2.4",
      "resolved": "http://packages.je-labs.com/npm/private-npm/mocha-trx-reporter/-/mocha-trx-reporter-3.2.4.tgz",
      "integrity": "sha512-hY4rHfzl49TgmgfkkgCskQIiOmi8J8h+/XcuPNz3y5HtdebD7uOKY6o+7LZVB/xg+3zfwmJ+weXqpinnVsJ5kA==",
      "dev": true,
      "requires": {
        "node-trx": "^0.9.1"
      }
    }

**Comment by smarandav** [comment]
I am looking at the mocha repo and I can see that  isPending has '@private' attribute vs the skip one for instance which has an explicit definition as @public & @memberof Mocha.Runnable?

https://github.com/mochajs/mocha/blob/cb5eb8ed42abfd0d63c5013353843f1208ff6582/lib/runnable.js#L142

vs

https://github.com/mochajs/mocha/blob/cb5eb8ed42abfd0d63c5013353843f1208ff6582/lib/runnable.js#L132

**Comment by pmoleri** [comment]
> I am looking at the mocha repo and I can see that isPending has '@Private' attribute vs the skip one for instance which has an explicit definition as @public & @memberof Mocha.Runnable?

I see what  you mean. Although the official [XUnit reporter](https://github.com/mochajs/mocha/blob/cb5eb8ed42abfd0d63c5013353843f1208ff6582/lib/reporters/xunit.js#L183) also uses this method.
It seems that there's no clear official way to get the pending state of a test.

> I have doubled checked and I am using latest version of mocha in both my packages that need it (cypress-multi-reporters, mocha-trx-reporter).

Don't you also have `cypress` as a dependency? Have you tried updated this one?
Could you check the actual resolved version of `mocha`? Just look for occurrences of `"mocha": {` in your package-lock.json.

**Comment by smarandav** [comment]
> > I am looking at the mocha repo and I can see that isPending has '@Private' attribute vs the skip one for instance which has an explicit definition as @public & @memberof Mocha.Runnable?
> 
> I see what you mean. Although the official [XUnit reporter](https://github.com/mochajs/mocha/blob/cb5eb8ed42abfd0d63c5013353843f1208ff6582/lib/reporters/xunit.js#L183) also uses this method.
> It seems that there's no clear official way to get the pending state of a test.
>
I think xUnit reporter is failing with the same error!

> > I have doubled checked and I am using latest version of mocha in both my packages that need it (cypress-multi-reporters, mocha-trx-reporter).
> 
> Don't you also have `cypress` as a dependency? Have you tried updated this one?
> Could you check the actual resolved version of `mocha`? Just look for occurrences of `"mocha": {` in your package-lock.json.

Cypress does not depend on mocha at all, only those two packages I mentioned above do and I do not have any hardcoded dependency of mocha in my package-lock.json file.

**Comment by pmoleri** [comment]
> Cypress does not depend on mocha at all, only those two packages I mentioned above do and I do not have any hardcoded dependency of mocha in my package-lock.json file.

Ok, I was assuming it was, I dont know anything about Cypress. However, someone should be requiring Mocha beacuse it's a peerDependency in both `mocha-trx-reporter@3.2.4` and [cypress-multi-reporters@1.4.0](https://github.com/YOU54F/cypress-multi-reporters/blob/v1.4.0/package.json#L53), that means that both reporters rely on someone else requiring `mocha => 3.1.2`.

You could try `npm install --save-dev mocha@latest`, but my understanding from issue https://github.com/cypress-io/cypress/issues/4652 is that Cypress is in fact bringing its own mocha version (a pretty old one).

**Comment by smarandav** [comment]
ok, thanks for looking into it. 
My issue is with latest version of mocha and the error I have is in the mocha-trx-reporter [here](https://github.com/Infragistics/mocha-trx-reporter/blob/af536418df586b6fa544267b8a3ff5c5f13adef7/lib/trx.js#L92))

TypeError: test.isPending is not a function
    at C:\source\RestaurantClaimsWeb\node_modules\mocha-trx-reporter\lib\trx.js:92:22
    at Array.forEach (<anonymous>:null:null)
    at Runner.<anonymous> (C:\source\RestaurantClaimsWeb\node_modules\mocha-trx-reporter\lib\trx.js:91:27)
    at Runner.emit (events.js:208:15)
    at Reporter.emit (C:\Users\smaranda.vladoiu\AppData\Local\Cypress\Cache\3.8.3\Cypress\resources\app\packages\server\lib\reporter.js:234:55)
    at Object.onMocha (C:\Users\smaranda.vladoiu\AppData\Local\Cypress\Cache\3.8.3\Cypress\resources\app\packages\server\lib\project.js:359:18)
    at Socket.<anonymous> (C:\Users\smaranda.vladoiu\AppData\Local\Cypress\Cache\3.8.3\Cypress\resources\app\packages\server\lib\socket.js:303:32)
    at Socket.emit (events.js:203:13)
    at C:\Users\smaranda.vladoiu\AppData\Local\Cypress\Cache\3.8.3\Cypress\resources\app\packages\socket\node_modules\socket.io\lib\socket.js:528:12
    at processTicksAndRejections (internal/process/task_queues.js:75:11)

**Comment by smarandav** [comment]
And my question is: does that isPending() method gets exposed outside the Runnable class in mocha as I can see it has the '@private' attribute

https://github.com/mochajs/mocha/blob/cb5eb8ed42abfd0d63c5013353843f1208ff6582/lib/runnable.js#L142

**Comment by pmoleri** [comment]
> And my question is: does that isPending() method gets exposed outside the Runnable class in mocha as I can see it has the '@Private' attribute.

Yes JS doesn't have a real notion of private methods, that's only a documentation annotation.
Everything works fine when not used in Cypress.

BTW, this is the mocha dependency on [Cypress@4.4.1](https://github.com/cypress-io/cypress/blob/v4.4.1/packages/server/package.json#L84). I don't know what version are you running. Could you try updating to Cypress >=4.5.0?

**Comment by smarandav** [comment]
I have "cypress": "^4.7.0",

**Comment by smarandav** [comment]
but I do have another package that has hardcoded cypress dependency,

"@vue/cli-plugin-e2e-cypress": {
      "version": "4.4.1",
      "resolved": "http://packages.je-labs.com/npm/private-npm/@vue/cli-plugin-e2e-cypress/-/cli-plugin-e2e-cypress-4.4.1.tgz",
      "integrity": "sha1-n2zA7YJDrVc6nzMZzyQ7MI7F07A=",
      "dev": true,
      "requires": {
        "@vue/cli-shared-utils": "^4.4.1",
        "cypress": "^3.8.3",
        "eslint-plugin-cypress": "^2.10.3"
      },

**Comment by pmoleri** [comment]
Well, that's really confusing now. From what I've seen Cypress 4.7.0 is using a modern mocha version, even if you have that other dependency I don't think it should be an issue.
Somehow, Cypress is getting in the way and something that works directly with Mocha fails when running from Crypess.
I can only suggest you to fork the project and tweak it in a way that doesn't rely on isPending() method.

Anyway, I do recommend you to put ^7.0.0 as a top dependency in your project. Why? Because both reporters depend on it, and when they do `require("mocha")` they will get an unknown version that may be incompatible with them.
